---
title: "Overlap Map & RadViz2D"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(MixSim)
library(RColorBrewer)
library(MASS)
library(freqparcoord)
library(expm)
library(grDevices)
library(radviz3d)
library(rgl)

source("modradviz2d-2.R")

```

```{r}
##
## Display the map of pairwise overlap measures of Maitra and Melnykov
## (JCGS, 2012)
##
## overlap.mat = matrix of total pairwise overlaps (necessarily symmetric)
## map.col = colormap for the mapping
## linescol = color for the lines drawing the squares
## map.range = range of the overlap map (default: minimum and maximum of lower
##               triangle of the matrix)
## lab.col = color of the labels (same as nrow(matrix) if provided)
## lab.cex = character size of the label
## map.cex = character size of the overlap values laid on the map
## legend.cex = character size of the legend text (does not work always)
##
## provides map of overlap values for each group of mixture model
##
## written Ranjan Maitra, Ames, IA 50011-1210, June 28, 2009
##
## modified Ranjan Maitra, Ames, IA 50011-1090, December 23, 2016.
## last modified Ranjan Maitra, Ames, IA 50011-1090, October 31, 2020.
##
## modification to bring in specifications for label color, labels, maps and
## legend character size; subsequently change default color of map and lines
##

overlap.map <-
    function(overlap.mat, map.col = RColorBrewer::brewer.pal(name = "PuRd", n = 9), linescol = "#1D91C0", map.range = NULL, lab = NULL, lab.col = 1, lab.cex = 5, map.cex = 5, legend.cex = 1, font = 1, scale = NULL, scale.pos = -2, legend.width = 1)
{
    oxmat <- overlap.mat
    oxmat[lower.tri(oxmat)] <- NA
    diag(oxmat) <- NA
    p <- ncol(oxmat)
    if(is.null(lab)){
      lab <- 1:p
    }
    newox <- oxmat[-p, -1]
    newox <- cbind(rbind(NA, newox), NA)[, p:1]

    layout(matrix(c(rep(1, 4*p^2), rep(2, 2*p), rep(3, 2*p), rep(4, 2*p), rep(4, 2*p)), nrow = 2*p, ncol = 2*p + 4 ))
    ##  layout(matrix(c(rep(1, p^2), rep(2, p), rep(3, p), rep(4, p)), nrow = p, ncol = p + 3))

    
    par(mar = c(0.1,0.1,0.75,0.1))
    if (is.null(map.range)) map.range <- range(newox, na.rm = T)  
    image(x = 1:p, y = 1:p, z = newox, axes = F, xlab = "", ylab = "", #col = brewer.pal(9, "GnBu"))
          col = map.col, zlim = map.range)
    text(y = 2:p, x = rep(1, p-1), labels = lab[p:2], cex = lab.cex, font = font, col = lab.col[p:2])
    text(x = 2:p, y = rep(1, (p-1)), labels = lab[1:(p-1)], cex = lab.cex, font = font, col = lab.col[1:(p-1)])
    if (!is.null(scale)){
       text(x = p-scale.pos, y = p+0.2, labels = scale, cex = map.cex)
    }
   


    for(i in 1:p) {
        for(j in i:p) {
            lines(x = c(i+0.5, i+0.5), y = c(p-j+1,p-j)+1.5, col = linescol, lwd = 0.5)
            lines(y = c(i+0.5, i+0.5), x = c(p-j+1,p-j)+1.5, col = linescol, lwd = 0.5)
        }
    }
    for(i in 2:p) text(x=1:p, y = i, labels = round(newox[,i], 2),
                       col = ifelse(newox[,i] < median(map.range), "black", "white"), cex = map.cex)

   frame()

    # savepar <- par(cex=0.75, lwd=0.25, mar = c(1, 0.5, 1, 2),
    #                 xaxs="i", yaxs="i")
    
    savepar <- par(cex=0.75, lwd=0.25, mar = c(0.5, 0.5, 0.5, 0.5),
                   xaxs="i", yaxs="i")
    # if (legend){
    plot.new()
    length.col <- length(map.col) + 1
    ra <- seq(from = map.range[1], to = map.range[2], length=length.col)
    plot.window(xlim=c(0,0.1), ylim= c(map.range[1], map.range[2]))
    rect(0, ra[-length.col], legend.width, ra[-1], col = map.col, border = NULL)
    axis(4, at = ra, labels = round(ra, digits = 2), las = 1, cex.axis = legend.cex, line = NA)
    

    rect(0, 1, legend.width, ra[length.col], col = NULL)
    frame()
    }

```

<table width="500" border="0" cellpadding="0">
<tr>

<td align="center" valign="center">
```{r}
load("sim_data_5.rda")
sim.palette = sim_pal <- brewer.pal(8,"Dark2")[c(5,8,4,7,3)]
df <- sim_data[[1]]
overlap.map((2*overlap_mat_sim[[1]] - diag(5))*1000, lab.col = sim_pal, scale = expression("("%*%10^-3~")"), map.cex = 2.75, lab.cex = 4, legend.cex = 1.5, font = 2, scale.pos = 0.35, legend.width = 0.1)
```
<br />
(i) Overlap Map, $p = 5, \ddot\omega = 0.001$ 
</td>

<td align="center" valign="center">
```{r}
df <- sim_data[[1]]
modradviz2d(x = df[,-1], cl = df$class, modify = F, 
            coord.labels = colnames(df[,-1]), class.labels = NULL,
            palette = sim.palette, opt.axis.order = F)
```
<br />
(iv) RadViz2D, $p = 5, \ddot\omega = 0.001$ 
</td>

</tr>
<tr>

<td align="center" valign="center">
```{r}
df <- sim_data[[2]]
overlap.map((2*overlap_mat_sim[[2]] - diag(5))*100, lab.col = sim_pal, scale = expression("("%*%10^-2~")"), map.cex = 2.75, lab.cex = 4, legend.cex = 1.5, font = 2, scale.pos = 0.35, legend.width = 0.1)
```
<br />
(i) Overlap Map, $p = 5, \ddot\omega = 0.01$ 
</td>

<td align="center" valign="center">
```{r}
df <- sim_data[[2]]
modradviz2d(x = df[,-1], cl = df$class, modify = F, 
            coord.labels = colnames(df[,-1]), class.labels = NULL,
            palette = sim.palette, opt.axis.order = F)
```
<br />
(iv) RadViz2D, $p = 5, \ddot\omega = 0.01$ 
</td>

</tr>
<tr>

<td align="center" valign="center">
```{r}
df <- sim_data[[3]]
overlap.map((2*overlap_mat_sim[[3]] - diag(5))*100, lab.col = sim_pal, scale = expression("("%*%10^-2~")"), map.cex = 2.75, lab.cex = 4, legend.cex = 1.5, font = 2, scale.pos = 0.35, legend.width = 0.1)
```
<br />
(i) Overlap Map, $p = 5, \ddot\omega = 0.05$
</td>

<td align="center" valign="center">
```{r}
df <- sim_data[[3]]
modradviz2d(x = df[,-1], cl = df$class, modify = F, 
            coord.labels = colnames(df[,-1]), class.labels = NULL,
            palette = sim.palette, opt.axis.order = F)
```
<br />
(v) RadViz2D, $p = 5, \ddot\omega = 0.05$ 
</td>

</tr>

</table>