---
title: "RadViz3D"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(MixSim)
library(RColorBrewer)
library(MASS)
library(freqparcoord)
library(expm)
library(grDevices)
library(radviz3d)
library(rgl)

```


```{r}
set.seed(2020)
res_radviz <- list()
sim.palette <- brewer.pal(8,"Dark2")[c(5,8,4,7,3)]
# load dataset:sim_data from the radviz3d package
for (i in 1:3){
  df <- sim_data[[i]]
  radialvis3d(data = df[,-1], cl = factor(df$class), domrp = F, doGtrans = F, lwd = 2, 
            alpha = 0.325, pradius = 0.02, color = sim.palette, class.labels = NULL)
  rgl::rgl.viewpoint(zoom = 0.6)
  res_radviz[[i]] <- rgl::rglwidget()
}

```


<table width="500" border="0" cellpadding="0">


<tr>
<td align="center" valign="center">
```{r}
res_radviz[[1]]
```
(i) RadViz3D, $p = 5, \ddot\omega = 0.001$ 
<br />
</td>

</tr>
</tr>

<td align="center" valign="center">
```{r}
res_radviz[[2]]
```
(ii) RadViz3D, $p = 5, \ddot\omega = 0.01$ 
<br />
</td>

</tr>
</tr>

<td align="center" valign="center">
```{r}
res_radviz[[3]]
```
(iii) RadViz3D, $p = 5, \ddot\omega = 0.05$
<br />
</td>

</tr>
</table>