---
title: "t-SNE"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, cache = T)
```

```{r}
source("stars.R")

viz2d_3d <- function(x, angles =  2*pi*(0:(ncol(x)-1))/ncol(x)) {
  y <- apply(X = x, MARGIN = 2, FUN = function(z)((z - min(z))/(max(z) - min(z))))
  sy <- rowSums(y)/ncol(y)
  y <- apply(X = y, MARGIN = 1, FUN = function(z)(z/sum(z)))
  y <- t(y)
  pr <- cbind(cos(angles), sin(angles))
  xproj <- cbind(y %*% pr, sy)
}

# {viz3d} function based on Artero and Oliveira's paper.
viz3d <- function(x, angles =  2*pi*(0:(ncol(x)-1))/ncol(x)) {
  y <- apply(X = x, MARGIN = 2, FUN = function(z)((z - min(z))/(max(z) - min(z))))
  #    x <- apply(X = y, MARGIN = 1, FUN = function(z)(z/sum(z)))
  #    x <- t(x)
  pr <- cbind(cos(angles), sin(angles), 1)
  xproj <- y %*% pr / ncol(y)
}

# color palette
load("colpal.rda")
dk.palette = senator.palette = c(rgb(red = 173, green = 216, blue = 230, max = 255), rgb(max = 255, red = 139, green = 0, blue = 0))

library(MixSim)
library(MASS)
library(expm)
library(grDevices)
library(freqparcoord)
library(Rtsne)
library(Rdimtools)
library(radviz3d)
library(rgl)
library(uwot)
library(RColorBrewer)

```

```{r}
load("datasets/sim_data.rda")
set.seed(2020)
res_tsne <- list()
for (i in 1:length(omegas)){
  sn.df <- sim_data[[i]]
  class <- sn.df[,ncol(sn.df)]
  tsne_res <- Rtsne(as.matrix(sn.df[,-ncol(sn.df)]), dims = 3,
                    perplexity = min(500, floor((nrow(sn.df) -1)/3)),
                    check_duplicates = F,
                    verbose = F,
                    max_iter = 500
                    )
  # umap_res <- umap(as.matrix(sn.g.df[,-20243]), n_components = 3)
  res1 = data.frame(tsne_res$Y, class)
  colnames(res1) = c("x","y","z","class")
  # open 3d window
  
  # resize window
  par3d(windowRect = c(100, 100, 612, 612))
  # plot
  with(res1, plot3d(axes = F, x,y,z, type="s",size = 0.75, 
                    col = brewer.pal(5,"Paired")[as.numeric(class)]))
  box3d()
  res_tsne[[i]] <- rglwidget()
}
```


<table width="500" border="0" cellpadding="0">

<tr>

<td align="center" valign="center">
```{r}
res_tsne[[1]]
```
(i) t-SNE, omega = 0.0001
<br />
</td>


</tr>

<tr>

<td align="center" valign="center">
```{r}
res_tsne[[2]]
```
(ii) t-SNE, omega = 0.001
<br />
</td>


</tr>

<tr>

<td align="center" valign="center">
```{r}
res_tsne[[3]]
```
(iii) t-SNE, omega = 0.01
<br />
</td>


</tr>

<tr>

<td align="center" valign="center">
```{r}
res_tsne[[4]]
```
(iv) t-SNE, omega = 0.05
<br />
</td>


</tr>

<tr>

<td align="center" valign="center">
```{r}
res_tsne[[5]]
```
(v) t-SNE, omega = 0.25
<br />
</td>
</tr>
</table>
